puts rand(1..2).to_s
puts rand(1..2).to_s
puts rand(1..2).to_s
puts rand(1..2).to_s
puts rand(1..2).to_s
puts rand(1..2).to_s
puts rand(1..2).to_s
puts rand(1..2).to_s
puts rand(1..2).to_s
puts rand(1..2).to_s
